#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _ensure_import_paths() -> None:
    root = _repo_root()
    src = str(root / "src")
    if src not in sys.path:
        sys.path.insert(0, src)

    try:
        import pydantic  # noqa: F401
    except ModuleNotFoundError:
        stubs = str(root / "tests" / "stubs")
        if stubs not in sys.path:
            sys.path.insert(0, stubs)


def _jsonish(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, dict)):
        return json.dumps(value, ensure_ascii=False)
    text = str(value)
    return text


def _render_cn() -> str:
    from mika_chat_core.webui.config_env import field_default, field_kind
    from mika_chat_core.webui.config_schema import CONFIG_UI_SCHEMA, env_key_for_field

    lines: list[str] = []
    lines.append("# 配置参考")
    lines.append("")
    lines.append("> 本页由 `scripts/gen_config_docs.py` 自动生成。请勿手改，以免再次过时。")
    lines.append("")
    lines.append("## 最小必填")
    lines.append("")
    lines.append("```env")
    lines.append('LLM_API_KEY="YOUR_API_KEY"')
    lines.append("MIKA_MASTER_ID=123456789")
    lines.append("```")
    lines.append("")
    lines.append("说明：`LLM_API_KEY` 与 `LLM_API_KEY_LIST` 二选一即可。")
    lines.append("")

    for section in CONFIG_UI_SCHEMA:
        section_name = str(section.get("name") or "").strip() or "配置"
        lines.append(f"## {section_name}")
        lines.append("")
        lines.append("| 字段 | 环境变量 | 类型 | 默认值 | 说明 |")
        lines.append("|------|----------|------|--------|------|")

        for field in section.get("fields", []):
            key = str(field.get("key") or "").strip()
            if not key:
                continue
            env_key = env_key_for_field(key)
            kind = field_kind(key)
            default = _jsonish(field_default(key))

            desc = str(field.get("description") or "").strip()
            hint = str(field.get("hint") or "").strip()
            tags: list[str] = []
            if field.get("secret"):
                tags.append("secret")
            if field.get("advanced"):
                tags.append("advanced")
            tag_text = f"[{', '.join(tags)}] " if tags else ""

            explain = f"{tag_text}{desc}"
            if hint:
                explain = f"{explain}<br/>{hint}"

            lines.append(f"| `{key}` | `{env_key}` | `{kind}` | `{default}` | {explain} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_en() -> str:
    from mika_chat_core.webui.config_env import field_default, field_kind
    from mika_chat_core.webui.config_schema import CONFIG_UI_SCHEMA, env_key_for_field

    lines: list[str] = []
    lines.append("# Configuration")
    lines.append("")
    lines.append("> This page is generated by `scripts/gen_config_docs.py`. Do not edit manually.")
    lines.append("")
    lines.append("## Minimum required")
    lines.append("")
    lines.append("```env")
    lines.append('LLM_API_KEY="YOUR_API_KEY"')
    lines.append("MIKA_MASTER_ID=123456789")
    lines.append("```")
    lines.append("")
    lines.append("`LLM_API_KEY` and `LLM_API_KEY_LIST` are alternatives (choose one).")
    lines.append("")
    lines.append("## Reference")
    lines.append("")

    lines.append("| Env Key | Type | Default |")
    lines.append("|---------|------|---------|")
    for section in CONFIG_UI_SCHEMA:
        for field in section.get("fields", []):
            key = str(field.get("key") or "").strip()
            if not key:
                continue
            env_key = env_key_for_field(key)
            kind = field_kind(key)
            default = _jsonish(field_default(key))
            lines.append(f"| `{env_key}` | `{kind}` | `{default}` |")

    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _write_or_check(path: Path, content: str, *, check: bool) -> None:
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return

    old = ""
    if path.exists():
        old = path.read_text(encoding="utf-8")
    if old == content:
        return

    diff = "\n".join(
        difflib.unified_diff(
            old.splitlines(),
            content.splitlines(),
            fromfile=str(path),
            tofile=str(path),
            lineterm="",
        )
    )
    raise SystemExit(f"generated docs out of date:\n{diff}\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated docs differ from repo files")
    args = parser.parse_args(argv)

    _ensure_import_paths()

    root = _repo_root()
    cn_path = root / "docs" / "guide" / "configuration.md"
    en_path = root / "docs" / "en" / "guide" / "configuration.md"

    cn = _render_cn()
    en = _render_en()

    _write_or_check(cn_path, cn, check=bool(args.check))
    _write_or_check(en_path, en, check=bool(args.check))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

