"""MikaClient 相关常量。"""

# UUID / ID
UUID_SHORT_ID_LENGTH = 8

# 内存上下文：允许的最大历史条数 = max_context * 2
CONTEXT_HISTORY_MULTIPLIER = 2

# 诊断/日志预览长度
CONTEXT_DIAGNOSTIC_TAIL_COUNT = 3
HISTORY_MESSAGE_PREVIEW_CHARS = 80
API_CONTENT_DEBUG_MIN_CHARS = 200
API_CONTENT_DEBUG_PREVIEW_CHARS = 500
RAW_MODEL_REPLY_PREVIEW_CHARS = 300
ERROR_RESPONSE_BODY_PREVIEW_CHARS = 500

# chat 默认重试与降级
DEFAULT_CHAT_RETRY_COUNT = 2
MAX_CONTEXT_DEGRADATION_LEVEL = 2
EMPTY_REPLY_RETRY_DELAY_SECONDS = 0.5

# 指数退避：wait_time = 2 ** (2 - retry_count)
SERVER_ERROR_RETRY_BACKOFF_BASE = 2
SERVER_ERROR_RETRY_EXPONENT_OFFSET = 2

# 主动发言判决：日志截断
PROACTIVE_JUDGE_ERROR_PREVIEW_CHARS = 100
PROACTIVE_JUDGE_RAW_CONTENT_SHORT_PREVIEW_CHARS = 100
PROACTIVE_JUDGE_RAW_CONTENT_ERROR_PREVIEW_CHARS = 200
PROACTIVE_JUDGE_SERVER_RESPONSE_PREVIEW_CHARS = 500

MEMORY_SESSION_COUNTER_MAX_SIZE = 2048
TOOL_SCHEMA_AUTO_THRESHOLD_DEFAULT = 10
TOOL_SCHEMA_FALLBACK_TTL_DEFAULT = 600
